# Required
version: 2

# Image to use
build:
  image: testing
  os: "ubuntu-20.04"
  tools:
    python: "3.7"

# Configuration
python:
  version: 3.9
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
